repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make -C ptest pytest_check
        language: system
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: make -C ptest ruff_check
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: make -C ptest black_check
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: make -C ptest mypy_check
        language: system
        pass_filenames: false
      - id: tomlsort
        name: tomlsort
        entry: make -C ptest tomlsort_check
        language: system
        pass_filenames: false
