cd alexnet && zip -r ../alexnet.mar . && cd ..
cd caffenet && zip -r ../caffenet.mar . && cd ..
cd FERPlus && zip -r ../FERPlus.mar . && cd ..
cd inception-bn && zip -r ../inception-bn.mar . && cd ..
cd lstm_ptb && zip -r ../lstm_ptb.mar . && cd ..
cd nin && zip -r ../nin.mar . && cd ..
cd onnx-arcface-resnet100 && zip -r ../onnx-arcface-resnet100.mar . && cd ..
cd onnx-duc && zip -r ../onnx-duc.mar . && cd ..
cd onnx-inception_v1 && zip -r ../onnx-inception_v1.mar . && cd ..
cd onnx-mobilenet && zip -r ../onnx-mobilenet.mar . && cd ..
cd onnx-resnet101v1 && zip -r ../onnx-resnet101v1.mar . && cd ..
cd onnx-resnet101v2 && zip -r ../onnx-resnet101v2.mar . && cd ..
cd onnx-resnet152v1 && zip -r ../onnx-resnet152v1.mar . && cd ..
cd onnx-resnet152v2 && zip -r ../onnx-resnet152v2.mar . && cd ..
cd onnx-resnet18v1 && zip -r ../onnx-resnet18v1.mar . && cd ..
cd onnx-resnet18v2 && zip -r ../onnx-resnet18v2.mar . && cd ..
cd onnx-resnet34v1 && zip -r ../onnx-resnet34v1.mar . && cd ..
cd onnx-resnet34v2 && zip -r ../onnx-resnet34v2.mar . && cd ..
cd onnx-resnet50v1 && zip -r ../onnx-resnet50v1.mar . && cd ..
cd onnx-resnet50v2 && zip -r ../onnx-resnet50v2.mar . && cd ..
cd onnx-squeezenet && zip -r ../onnx-squeezenet.mar . && cd ..
cd onnx-vgg16_bn && zip -r ../onnx-vgg16_bn.mar . && cd ..
cd onnx-vgg16 && zip -r ../onnx-vgg16.mar . && cd ..
cd onnx-vgg19_bn && zip -r ../onnx-vgg19_bn.mar . && cd ..
cd onnx-vgg19 && zip -r ../onnx-vgg19.mar . && cd ..
cd resnet-152 && zip -r ../resnet-152.mar . && cd ..
cd resnet-18 && zip -r ../resnet-18.mar . && cd ..
cd resnet50_ssd && zip -r ../resnet50_ssd.mar . && cd ..
cd resnext-101-64x4d && zip -r ../resnext-101-64x4d.mar . && cd ..
cd squeezenet_v1.1 && zip -r ../squeezenet_v1.1.mar . && cd ..
cd squeezenet_v1.1 && zip -r ../squeezenet_v1.1.mar . && cd ..
cd squeezenet_v1.2 && zip -r ../squeezenet_v1.2.mar . && cd ..
cd vgg16 && zip -r ../vgg16.mar . && cd ..
cd vgg19 && zip -r ../vgg19.mar . && cd ..


