cp -rf ~/source/mxnet-model-server/examples/model_service_template/* alexnet
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* caffenet
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* FERPlus
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* inception-bn
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* lstm_ptb
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* nin
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-arcface-resnet100
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-duc
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-inception_v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-mobilenet
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet101v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet101v2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet152v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet152v2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet18v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet18v2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet34v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet34v2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet50v1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-resnet50v2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-squeezenet
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-vgg16_bn
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-vgg16
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-vgg19_bn
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* onnx-vgg19
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* resnet-152
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* resnet-18
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* resnet50_ssd
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* resnext-101-64x4d
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* shufflenet
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* squeezenet_v1.1
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* squeezenet_v1.2
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* vgg16
cp -rf ~/source/mxnet-model-server/examples/model_service_template/* vgg19

