mkdir -p alexnet && cd alexnet && unzip ../alexnet.mar && cd ..
mkdir -p caffenet && cd caffenet && unzip ../caffenet.mar && cd ..
mkdir -p FERPlus && cd FERPlus && unzip ../FERPlus.mar && cd ..
mkdir -p inception-bn && cd inception-bn && unzip ../inception-bn.mar && cd ..
mkdir -p lstm_ptb && cd lstm_ptb && unzip ../lstm_ptb.mar && cd ..
mkdir -p nin && cd nin && unzip ../nin.mar && cd ..
mkdir -p onnx-arcface-resnet100 && cd onnx-arcface-resnet100 && unzip ../onnx-arcface-resnet100.mar && cd ..
mkdir -p onnx-duc && cd onnx-duc && unzip ../onnx-duc.mar && cd ..
mkdir -p onnx-inception_v1 && cd onnx-inception_v1 && unzip ../onnx-inception_v1.mar && cd ..
mkdir -p onnx-mobilenet && cd onnx-mobilenet && unzip ../onnx-mobilenet.mar && cd ..
mkdir -p onnx-resnet101v1 && cd onnx-resnet101v1 && unzip ../onnx-resnet101v1.mar && cd ..
mkdir -p onnx-resnet101v2 && cd onnx-resnet101v2 && unzip ../onnx-resnet101v2.mar && cd ..
mkdir -p onnx-resnet152v1 && cd onnx-resnet152v1 && unzip ../onnx-resnet152v1.mar && cd ..
mkdir -p onnx-resnet152v2 && cd onnx-resnet152v2 && unzip ../onnx-resnet152v2.mar && cd ..
mkdir -p onnx-resnet18v1 && cd onnx-resnet18v1 && unzip ../onnx-resnet18v1.mar && cd ..
mkdir -p onnx-resnet18v2 && cd onnx-resnet18v2 && unzip ../onnx-resnet18v2.mar && cd ..
mkdir -p onnx-resnet34v1 && cd onnx-resnet34v1 && unzip ../onnx-resnet34v1.mar && cd ..
mkdir -p onnx-resnet34v2 && cd onnx-resnet34v2 && unzip ../onnx-resnet34v2.mar && cd ..
mkdir -p onnx-resnet50v1 && cd onnx-resnet50v1 && unzip ../onnx-resnet50v1.mar && cd ..
mkdir -p onnx-resnet50v2 && cd onnx-resnet50v2 && unzip ../onnx-resnet50v2.mar && cd ..
mkdir -p onnx-squeezenet && cd onnx-squeezenet && unzip ../onnx-squeezenet.mar && cd ..
mkdir -p onnx-vgg16_bn && cd onnx-vgg16_bn && unzip ../onnx-vgg16_bn.mar && cd ..
mkdir -p onnx-vgg16 && cd onnx-vgg16 && unzip ../onnx-vgg16.mar && cd ..
mkdir -p onnx-vgg19_bn && cd onnx-vgg19_bn && unzip ../onnx-vgg19_bn.mar && cd ..
mkdir -p onnx-vgg19 && cd onnx-vgg19 && unzip ../onnx-vgg19.mar && cd ..
mkdir -p resnet-152 && cd resnet-152 && unzip ../resnet-152.mar && cd ..
mkdir -p resnet-18 && cd resnet-18 && unzip ../resnet-18.mar && cd ..
mkdir -p resnet50_ssd && cd resnet50_ssd && unzip ../resnet50_ssd.mar && cd ..
mkdir -p resnext-101-64x4d && cd resnext-101-64x4d && unzip ../resnext-101-64x4d.mar && cd ..
mkdir -p shufflenet && cd shufflenet && unzip ../shufflenet.mar && cd ..
mkdir -p shufflenet && cd shufflenet && unzip ../shufflenet.mar && cd ..
mkdir -p squeezenet_v1.2 && cd squeezenet_v1.2 && unzip ../squeezenet_v1.2.mar && cd ..
mkdir -p vgg16 && cd vgg16 && unzip ../vgg16.mar && cd ..
mkdir -p vgg19 && cd vgg19 && unzip ../vgg19.mar && cd ..

