FROM ubuntu:16.04

COPY install_built_tools.sh /tmp
RUN /tmp/install_built_tools.sh
RUN rm -f /tmp/install_built_tools.sh

COPY build_mxnet.sh /usr/local/mxnet/
COPY set_env.sh /usr/local/mxnet/
COPY config/libmxnet.ver /usr/local/mxnet/config/
COPY config/linux.mk /usr/local/mxnet/config/
COPY config/linux-mkl.mk /usr/local/mxnet/config/

ENV PATH="/usr/local/mxnet:${PATH}"

WORKDIR /mxnet
